branches:
  only:
    - master

language: android
sudo: false
jdk:
  - oraclejdk8

env:
global:
- ANDROID_TARGET=android-23
- BUILD_TOOLS=build-tools-23.0.3

android:
  components:
    - $BUILD_TOOLS
    - $ANDROID_TARGET
    - extra-android-support
    - extra-android-m2repository

licenses:
  - 'android-sdk-license-.+'

script:
  - ./gradlew :sdk:clean :sdk:test


cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository
