branches:
  only:
    - master

language: android
sudo: true
jdk:
  - oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-24
    - BUILD_TOOLS=build-tools-24.0.3

android:
  components:
    - $BUILD_TOOLS
    - $ANDROID_TARGET
    - extra-android-support
    - extra-android-m2repository

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - mkdirs '$ANDROID_HOME/licenses'
  - echo '8933bad161af4178b1185d1a37fbf41ea5269c55' >> '$ANDROID_HOME/licenses/android-sdk-license'
  - ./gradlew :sdk:clean :sdk:test


cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository
